#!/bin/bash
./run.sh TGAT REDDIT GNNLabStaticCache
./run.sh TGAT REDDIT GNNLabStaticCache
./run.sh TGAT WIKI GNNLabStaticCache
./run.sh TGAT WIKI GNNLabStaticCache
./run.sh TGAT MOOC GNNLabStaticCache
./run.sh TGAT MOOC GNNLabStaticCache
./run.sh TGAT LASTFM GNNLabStaticCache
./run.sh TGAT LASTFM GNNLabStaticCache
./run.sh TGAT REDDIT LFUCache
./run.sh TGAT REDDIT LRUCache
./run.sh TGAT REDDIT FIFOCache
./run.sh TGAT REDDIT LFUCache
./run.sh TGAT REDDIT LRUCache
./run.sh TGAT REDDIT FIFOCache
./run.sh TGAT WIKI LFUCache
./run.sh TGAT WIKI LRUCache
./run.sh TGAT WIKI FIFOCache
./run.sh TGAT WIKI LFUCache
./run.sh TGAT WIKI LRUCache
./run.sh TGAT WIKI FIFOCache
./run.sh TGAT MOOC LRUCache
./run.sh TGAT MOOC LFUCache
./run.sh TGAT MOOC FIFOCache
./run.sh TGAT MOOC LRUCache
./run.sh TGAT MOOC LFUCache
./run.sh TGAT MOOC FIFOCache
./run.sh TGAT LASTFM LRUCache
./run.sh TGAT LASTFM LFUCache
./run.sh TGAT LASTFM FIFOCache
./run.sh TGAT LASTFM LRUCache
./run.sh TGAT LASTFM LFUCache
./run.sh TGAT LASTFM FIFOCache
./run.sh TGAT MAG LRUCache
./run.sh TGAT MAG LFUCache
./run.sh TGAT MAG FIFOCache
./run.sh TGAT MAG LRUCache
./run.sh TGAT MAG LFUCache
./run.sh TGAT MAG FIFOCache
./run.sh TGAT GDELT LRUCache
./run.sh TGAT GDELT LFUCache
./run.sh TGAT GDELT FIFOCache
./run.sh TGAT GDELT LRUCache
./run.sh TGAT GDELT LFUCache
./run.sh TGAT GDELT FIFOCache
